name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker run -v "$(pwd)":/src ghcr.io/recmo/rust-static-build:1.63-x86_64 cargo build --release
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: tunxy
          path: ./target/x86*/release/tunxy
      
